### ISSUE TITLE
Cannot extract using Windows (Python 64bit)

### ISSUE THREAD

**Issue by lplpmc** [tnajdek/rafiki#2]
My lol path is C:\Riot\lol .. did i do something wrong? 

C:\Riot>python rafiki.py extract -s lol -f "hud/elements" -o extracted
Traceback (most recent call last):
  File "rafiki.py", line 75, in <module>
    collection = RafCollection(source_path)
  File "C:\Riot\raf.py", line 143, in **init**
    self.index[item] = RafArchive(os.path.join(path, item, filename))
  File "C:\Riot\raf.py", line 71, in **init**
    path = path.strip('\x00')
TypeError: Type str doesn't support the buffer API

C:\Riot>

**Comment by tnajdek** [comment]
Are you using Python 3 by any chance?   I've only tested it with Python 2 and did very little testing on windows.

Unfortunately I'm currently bit too busy to look into rafiki/hud-fixer again, will do as soon as I get some times on my hands.

**Comment by lplpmc** [comment]
Yup, running Python 2 fixed it..thanks! works like a charm was able to modify Game.cfg

**Comment by tnajdek** [comment]
cool!
